site_name: MkLorum
nav:
  - 主页: index.md
  - 教程:
    - C:
      - 第一章: Tutorial/C/chapter-1.md
      - 第二章: Tutorial/C/chapter-2.md
    - Java: Tutorial/Java.md
    - Python: Tutorial/Python.md
  - 关于我: about.md

#theme: readthedocs
